spring.application.name=Deeblr
# MySQL Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/deeblr_db
spring.datasource.username=jd542
spring.datasource.password=XUEWj6*Yh

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
